### ISSUE TITLE
Detach repo

### ISSUE THREAD

**Issue by rugk** [thermatk/FastHub-Libre#5]
Can you please detach this repo from the not Google-play-only version?

You can this either [do it manually](https://www.quora.com/Git-revision-control-How-can-one-detach-a-forked-project-in-GitHub#ld_fjxjzo_52503) **or** – which I recommend – just contact the GitHub support to do it for you.

This…
1. shows that this is a real maintained project and not just a repo of someone who (once) made a pull request
2. can (and IMHO should) still link to the original repo/website/author/… for crediting them, but you can do so in better ways (in the Readme, wiki or so)
3. allows searching in this repo on GitHub and
4. it just looks much nicer

**Comment by thermatk** [comment]
I don't think it will be necessary. I like the client and everything, but something is terribly wrong with its direction. Luckily, upstream claims to be feature complete, so one release a year will be enough 😄
