### ISSUE TITLE
App state not saved, when editing issue

### ISSUE THREAD

**Issue by rancidfrog** [thermatk/FastHub-Libre#7]
Currently only tested when adding issue and editing it,
For example, 
- open issue 
- add title 
- click on body
- switch to other app,
- click home
- select fasthub-libre

Fasthub-libre opens to home screen, main feed.
Whereas it should open back to body of issue you where working on

**Comment by thermatk** [comment]
I've heavily reduced the amount of patches, so will release a better 4.5.1 after upstream merges the changes to master. Otherwise, I would suspect it's an upstream issue altogether

**Comment by thermatk** [comment]
If https://github.com/thermatk/FastHub-Libre/releases/tag/4.5.1 doesn't help, than it's most probably an upstream issue

**Comment by ildar** [comment]
Might be good to add an issue template asking to check with upstream apk
